# https://docs.travis-ci.com/user/languages/android/
# https://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
# https://travis-ci.community/t/accept-license-for-android-build-tools-27-0-3-bug/549

language: android
dist: trusty
sudo: false
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "build-tools;29.0.2"
  - yes | sdkmanager "platforms;android-29"
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    #- build-tools-26.0.2

    # The SDK version used to compile your project
    #- android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - android-$ANDROID_EMULATOR_LEVEL
    - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_LEVEL
  licenses:
    - '.+'

env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_EMULATOR_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20

before_script:
  # Create and start emulator.
  - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew connectedAndroidTest